### ISSUE TITLE
Race condition on Win32 when invoking JThread::Start in parallel (and other mistakes)

### ISSUE THREAD

**Issue by Ext3h** [j0r1/JThread#1]
Attached is a patch fixing the following issues:

- When the same thread is started in parallel from two threads, a race condition can occur in jthread.cpp:78, as the `running` property is updated after the mutex is already unlocked. When this occurs, a deadlock, leaked handle or worse is the result.
- When `JThread::Kill` is called in parallel with `JThread::Start`, a race condition can occur. If that kill occurs anywhere between jthread.cpp:78 and jthread.cpp:92, the result is a deadlock of the `JThread::Start` call as `running` has already been reset to `false`.
- The return value from `_beginthreadex` is `INVALID_HANDLE_VALUE`, not `NULL`. In fact, `NULL` is actually a valid handle.
- `threadhandle` should be properly initialized, and returned to uninitialized state after invalidation. Just for the sake of making race conditions easier to debug.

[jthread.cpp.patch.txt](https://github.com/j0r1/JThread/files/838433/jthread.cpp.patch.txt)

Isn't "threadsafe" the one thing a threading library should be?...
Only checked the Windows implementation, and only the `JThread` class to be specific.

**Comment by Ext3h** [comment]
PS: Yeah, precisely the same issues in the pthread implementation as well. All patches (except for `INVALID_HANDLE_VALUE`) apply accordingly.

**Comment by j0r1** [comment]
Well spotted. I've personally never encountered a scenario where I'd try to call Start from different threads, and I normally kill a thread from the one that started it. But it should be fixed, of course.

Regarding the handle. When I look at the [docs for CreateThread](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682453(v=vs.85).aspx), it says "If the function fails, the return value is NULL". And the [docs for _beginthreadex](https://msdn.microsoft.com/en-us/library/kdzttdcb.aspx) say that "On an error, _beginthreadex returns 0".

**Comment by Ext3h** [comment]
Oh, my fault regarding the return value on `_beginthreadex`. Accidentally looked at `_beginthread` instead.

Double checked the range of value IDs for handles as well, looks like `0` is explictly excluded for thread handles: https://msdn.microsoft.com/en-us/library/windows/desktop/ms686746(v=vs.85).aspx

OK, so `0` is legit and sane default value.

**Comment by j0r1** [comment]
This should now be fixed in the repository. 

I am curious though: what kind of application are you using the library in that made you think of two Start calls or a simultaneous Start and Kill call?

**Comment by Ext3h** [comment]
Use case: Pretty expensive initialization for the object itself (risk of severy memory fragmentation if performed to often), and on top of that allocated hardware resources while the thread is running. So the instances (safely) exit their own thread as soon as not needed, and are started again whenever needed next. There are potentially multiple consumers trying to access (and beforehand start) the instances on demand. Since all other methods on the objects were made threadsafe, it was assumed that `Start` was as well.

Could probably be remodelled to avoid terminating the threads ever, just releasing the context on the hardware, but I guess you know legacy software. Definitely predating the availability of standarized C++11 threads.

The race condition with `Kill` never even occured in practice, fixing that was just routine.

**Comment by j0r1** [comment]
Very interesting! Thanks again for the patch!
